#!/bin/sh
# Fixture only — never executed. One annotated instance per alternative of the rule
# named in the file name; `# ruleid:` names the rule the next line must draw.
# Every host pattern in _DROP_HOSTS, then the four raw-IP forms (dotted, decimal, hex, IPv6).
# ruleid: sh-dropsite
curl -s https://pastebin.com/raw/x
# ruleid: sh-dropsite
curl -s https://paste.ee/p/x
# ruleid: sh-dropsite
curl -s https://hastebin.com/raw/x
# ruleid: sh-dropsite
curl -s https://dpaste.com/x
# ruleid: sh-dropsite
curl -s https://dpaste.org/x
# ruleid: sh-dropsite
curl -s https://ghostbin.co/x
# ruleid: sh-dropsite
curl -s https://rentry.co/x
# ruleid: sh-dropsite
curl -s https://transfer.sh/x
# ruleid: sh-dropsite
curl -s https://0x0.st/x
# ruleid: sh-dropsite
curl -s https://file.io/x
# ruleid: sh-dropsite
curl -s https://anonfiles.com/x
# ruleid: sh-dropsite
curl -s https://gofile.io/x
# ruleid: sh-dropsite
curl -s https://catbox.moe/x
# ruleid: sh-dropsite
curl -s https://abc-123.ngrok.io/x
# ruleid: sh-dropsite
curl -s https://abc-123.ngrok-free.app/x
# ruleid: sh-dropsite
curl -s https://abc-123.ngrok.dev/x
# ruleid: sh-dropsite
curl -s https://abc-123.trycloudflare.com/x
# ruleid: sh-dropsite
curl -s https://abc-123.loca.lt/x
# ruleid: sh-dropsite
curl -s https://abc-123.serveo.net/x
# ruleid: sh-dropsite
curl -s https://webhook.site/x
# ruleid: sh-dropsite
curl -s https://requestbin.com/x
# ruleid: sh-dropsite
curl -s https://requestbin.net/x
# ruleid: sh-dropsite
curl -s https://abc-123.pipedream.net/x
# ruleid: sh-dropsite
curl -s https://abc-123.requestcatcher.com/x
# ruleid: sh-dropsite
curl -s https://discord.com/api/webhooks/1/x
# ruleid: sh-dropsite
curl -s https://discordapp.com/api/webhooks/1/x
# ruleid: sh-dropsite
curl -s https://hooks.slack.com/services/x
# ruleid: sh-dropsite
curl -s https://abc-123.webhook.office.com/x
# ruleid: sh-dropsite
curl -s https://api.telegram.org/bot123/sendMessage
# ruleid: sh-dropsite
curl -s https://203.0.113.5/x
# ruleid: sh-dropsite
curl -s https://3405803781/x
# ruleid: sh-dropsite
curl -s https://0xcb00710f/x
# ruleid: sh-dropsite
curl -s https://[2001:db8::1]/x
# Two hosts on one line: one finding, so the dedupe is graded.
# ruleid: sh-dropsite
curl https://pastebin.com/raw/a https://paste.ee/b
