# Fixture only — never executed. One instance per member of the scanner's CONFUSABLE
# table (the selftest checks the two agree), then the shapes the guard must not hide.
# ruleid: uni-confusable
def reаd_data():
    pass
# ruleid: uni-confusable
xаy_0430 = 1
# ruleid: uni-confusable
xеy_0435 = 1
# ruleid: uni-confusable
xоy_043e = 1
# ruleid: uni-confusable
xрy_0440 = 1
# ruleid: uni-confusable
xсy_0441 = 1
# ruleid: uni-confusable
xуy_0443 = 1
# ruleid: uni-confusable
xхy_0445 = 1
# ruleid: uni-confusable
xіy_0456 = 1
# ruleid: uni-confusable
xјy_0458 = 1
# ruleid: uni-confusable
xѕy_0455 = 1
# ruleid: uni-confusable
xһy_04bb = 1
# ruleid: uni-confusable
xԁy_0501 = 1
# ruleid: uni-confusable
xԛy_051b = 1
# ruleid: uni-confusable
xԝy_051d = 1
# ruleid: uni-confusable
xАy_0410 = 1
# ruleid: uni-confusable
xВy_0412 = 1
# ruleid: uni-confusable
xЕy_0415 = 1
# ruleid: uni-confusable
xКy_041a = 1
# ruleid: uni-confusable
xМy_041c = 1
# ruleid: uni-confusable
xНy_041d = 1
# ruleid: uni-confusable
xОy_041e = 1
# ruleid: uni-confusable
xРy_0420 = 1
# ruleid: uni-confusable
xСy_0421 = 1
# ruleid: uni-confusable
xТy_0422 = 1
# ruleid: uni-confusable
xХy_0425 = 1
# ruleid: uni-confusable
xІy_0406 = 1
# ruleid: uni-confusable
xЈy_0408 = 1
# ruleid: uni-confusable
xЅy_0405 = 1
# ruleid: uni-confusable
xΟy_039f = 1
# ruleid: uni-confusable
xοy_03bf = 1
# ruleid: uni-confusable
xΑy_0391 = 1
# ruleid: uni-confusable
xΒy_0392 = 1
# ruleid: uni-confusable
xΕy_0395 = 1
# ruleid: uni-confusable
xΖy_0396 = 1
# ruleid: uni-confusable
xΗy_0397 = 1
# ruleid: uni-confusable
xΙy_0399 = 1
# ruleid: uni-confusable
xΚy_039a = 1
# ruleid: uni-confusable
xΜy_039c = 1
# ruleid: uni-confusable
xΝy_039d = 1
# ruleid: uni-confusable
xΡy_03a1 = 1
# ruleid: uni-confusable
xΤy_03a4 = 1
# ruleid: uni-confusable
xΥy_03a5 = 1
# ruleid: uni-confusable
xΧy_03a7 = 1
# ruleid: uni-confusable
xαy_03b1 = 1
# ruleid: uni-confusable
xεy_03b5 = 1
# ruleid: uni-confusable
xρy_03c1 = 1
# ruleid: uni-confusable
xτy_03c4 = 1
# ruleid: uni-confusable
xυy_03c5 = 1
# ruleid: uni-confusable
xχy_03c7 = 1
# ruleid: uni-confusable
xνy_03bd = 1
# ruleid: uni-confusable
xιy_03b9 = 1
# ruleid: uni-confusable
xκy_03ba = 1
# An accent elsewhere in the token does not switch the rule off.
# ruleid: uni-confusable
café.reаd()
# ruleid: uni-confusable
café_reаd = 2

# A run of three letters is a hit however they split; an escape prefix is dropped, the rest is not.
# ruleid: uni-confusable
dοg = 1
# ruleid: uni-confusable
print("\\nreаd the file")
