#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

# Colour only on a terminal that has it, and never when NO_COLOR is set (the
# no-color.org convention every colour-emitting helper below inherits).
if [[ -z "${NO_COLOR:-}" && -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)
WATCH=()          # copy-paste commands that follow something long-lived this run started

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    # explorer.exe exits 1 even when it opens the URL; don't let that
    # false-trigger the warn below.
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url" || true
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# _prompt "text" — the one prompt line both confirm gates share: the question
# in colour, the colour closed before the human types, then one line read into
# $reply (EOF reads as an empty reply, so no answer is a no).
_prompt() {
  printf '  %s? %s%s ' "$YELLOW" "$1" "$RESET"
  read -r reply || true
}

# confirm "question" — y/N gate for a step the wizard can undo; returns
# success on a y or Y. Anything else — including EOF — prints the abort line
# and returns 1, which ends a bare call under the library's -e with no
# summary: call it as `if confirm …; then …; else finish; exit 0; fi`. A
# second argument is a bug in the wizard, never a token gate — the
# irreversible gate is confirm_token: it names the call on stderr and
# returns 2.
confirm() {
  if [ "$#" -ne 1 ]; then
    printf '  %s✗ confirm "%s" was given a token — the irreversible gate is confirm_token%s\n' "$RED" "${1:-}" "$RESET" >&2
    return 2
  fi
  local reply=""
  _prompt "$1 [y/N]"
  [[ "$reply" =~ ^[Yy] ]] && return 0
  say "Aborted — that step was not run."
  return 1
}

# confirm_token "question" TOKEN — gate for the one act the wizard cannot
# undo (a cutover, a purge, a deletion): the human types TOKEN back —
# surrounding whitespace is ignored, case is not, and a `\r` from a CRLF
# paste is a no — and a `y` does not pass, because a wizard that has asked
# [y/N] at every stage has taught the hand to type y. An empty or missing
# TOKEN is a bug in the wizard (a value no stage captured), never a request
# for the y/N gate: it names the call on stderr and returns 2. On no it
# prints the abort line and returns 1, which ends a bare call under the
# library's -e with no summary — so call it as
# `if confirm_token …; then …; else finish; exit 0; fi`.
confirm_token() {
  if [ "$#" -lt 2 ] || [[ -z "$2" ]]; then
    printf '  %s✗ confirm_token "%s" was given an empty token — no stage captured it%s\n' "$RED" "${1:-}" "$RESET" >&2
    return 2
  fi
  local reply=""
  _prompt "$1 — type $2 to proceed:"
  [[ "$reply" == "$2" ]] && return 0
  say "Aborted — that step was not run."
  return 1
}

# preview CMD [ARGS...] — run a preview (a dry-run, a plan, a diff) and show
# its output indented, immediately before the confirm that approves the real
# thing. A preview is a snapshot the apply re-derives: after any change to its
# inputs — an edit, a pull, another stage's write — run it again before
# confirming, because the apply never reuses the preview's output and a stale
# one approves something else. Tolerates a non-zero exit: `kubectl diff` and `terraform plan
# -detailed-exitcode` exit non-zero precisely when there is something to show,
# and the library's -e would otherwise end the wizard there. The exit code is
# printed, never swallowed, so a preview that actually failed reads as one.
# The output streams through sed rather than landing in a temp file: a plan
# or diff routinely carries connection strings and tokens, and a Ctrl-C
# mid-preview must leave nothing on disk.
preview() {
  local rc=0
  printf '  %s▶ preview:%s %s\n' "$DIM" "$RESET" "$*"
  "$@" 2>&1 | sed 's/^/    /' || rc=$?
  if (( rc != 0 )); then
    note "preview exited $rc — for a diff or plan that means there is something to apply; for anything else, read the output before confirming"
  fi
  return 0
}

# watch CMD [ARGS...] — print the exact copy-paste command that follows a job
# this stage started (a deploy, a provisioning run, a background process), and
# record it so `finish` repeats it under its own heading for anything that
# outlives the wizard. Takes the command as words, like `preview`, or as one
# quoted string — both land whole.
watch() {
  WATCH+=("$*")
  printf '  %s⌛ watch it with:%s %s\n' "$BLUE" "$RESET" "$*"
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  if (( ${#WATCH[@]} )); then
    printf '\n'; say "${BOLD}still running — watch with:${RESET}"
    for w in "${WATCH[@]}"; do note "  $w"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=1

banner "Stripe setup"

# ── Example stage: replace with your real steps ───────────────────────────
stage "Stripe — API keys"
say "We'll grab your Stripe test keys and store them for local dev + CI."
open_url "https://dashboard.stripe.com/test/apikeys"
step "On the API keys page, copy the Publishable key (starts pk_test_)."
ask STRIPE_PUBLISHABLE_KEY "Paste the publishable key:"
step "Click 'Reveal test key' on the Secret key row, then copy it."
ask_secret STRIPE_SECRET_KEY "Paste the secret key:"
write_env STRIPE_PUBLISHABLE_KEY "$STRIPE_PUBLISHABLE_KEY"
write_env STRIPE_SECRET_KEY "$STRIPE_SECRET_KEY"
set_secret STRIPE_SECRET_KEY "$STRIPE_SECRET_KEY"   # CI needs this one
# ──────────────────────────────────────────────────────────────────────────

finish
